### PR TITLE
Add a section about API stubs

### PR DESCRIPTION
**Pull request by mysticfall**
A short introduction of [fake-bpy-module](https://github.com/nutti/fake-bpy-module), and [fake-bge-module](https://github.com/nutti/fake-bge-module).

Thanks [nutti](https://github.com/nutti)! :)

### CODE REVIEW

**Comment by mysticfall** [comment]
Thanks much! :)

**Comment by nutti** [comment]
@mysticfall @lordloki 

Thanks for introducing my tools at UPBGE document!
I'm very appreciate!

**Comment by youle31** [comment]
Thanks to you all!

**Comment by mysticfall** [comment]
By the way, how is it published to the website? Do we have some sort of a CI system for that?

Sorry to be impatient, but I can't deny that I'd like to see the new section on the website. :)

**Comment by lordloki** [comment]
It was compiled using Readthedocs CI.
But i think it is not compiling now as we pass of the 15min compilation limit.

I will have to compile myself and upload to new server (not ready yet).

**Comment by mysticfall** [comment]
@lordloki Oh, you don't have to hurry, I only asked because I wondered if there's any manual task that needs to be done :sweat_smile:

And please let me know if there's anything I could do. I feel a bit more comfortable about doing server stuffs than coding C++, so I may be able to help.

**Pull request merged**
